const dummyStaticNetworkConfig = [{
  'network_yaml': '#generated by ui form view\ninterfaces:\n  - name: DUMMY4\n    type: ethernet\n    state: up\n    ipv4:\n      address:\n        - ip: 0.0.0.0\n          prefix-length: 24\n      enabled: true\n      dhcp: false\n',
  'mac_interface_map': [{ 'mac_address': '01:23:45:67:89:AB', 'logical_nic_name': 'DUMMY4' }],
}];

export { dummyStaticNetworkConfig };
